# Generated by Django 4.2.4 on 2023-08-16 20:00

from django.db import migrations, models
import products.validate


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, validators=[products.validate.validate_price]),
        ),
    ]
